# shared/crypto.sh — encrypt/decrypt helpers for claude-on-a-stick (POSIX: Linux solid, macOS best-effort)
#
# This file is sourced by the builder (builders/posix/build.sh). It is NOT executed directly.
# It provides the ENCRYPT side used at build time (write config/oauth.enc) and a thin DECRYPT
# wrapper that mirrors payload/decrypt.sh so the builder can self-test the round-trip.
#
# On-disk format (VERIFIED round-trip with .NET / openssl / LibreSSL):
#     oauth.enc = salt[16] || iv[16] || AES-256-CBC(PKCS7) ciphertext
# KDF: PBKDF2-HMAC-SHA1, 300000 iterations, 32-byte key.
#   SHA1 is chosen ON PURPOSE: it is the digest of .NET's 3-arg Rfc2898DeriveBytes ctor and is
#   universally available across openssl 3 (`openssl kdf`), LibreSSL (perl fallback) and Windows.
#
# All key derivation produces the SAME 32 bytes across:
#   - python3 hashlib.pbkdf2_hmac('sha1', pw, salt, 300000, 32)
#   - openssl kdf ... PBKDF2  (OpenSSL 3, Linux)
#   - perl Digest::SHA hmac_sha1 PBKDF2 (macOS LibreSSL fallback)
#   - .NET Rfc2898DeriveBytes(pw, salt, 300000).GetBytes(32)  (Windows, crypto.ps1)
#
# Passwords and tokens are passed as function arguments / heredoc stdin; they are NEVER written
# to a temp file and NEVER passed on a command line where another implementation could observe
# them via the process table (we always feed openssl the derived KEY hex, not the password).

# ---------------------------------------------------------------------------
# cas_crypto_have <cmd>  -> 0 if command exists
# ---------------------------------------------------------------------------
cas_crypto_have() { command -v "$1" >/dev/null 2>&1; }

# ---------------------------------------------------------------------------
# cas_pbkdf2_keyhex <password> <salthex>  -> prints 64-char lowercase hex key (32 bytes)
#
# Derivation strategy, in order of preference:
#   1. python3  (preferred everywhere it exists — matches every other impl, no edge cases)
#   2. openssl 3 `openssl kdf` (Linux/OpenSSL 3; LibreSSL has NO kdf subcommand)
#   3. perl Digest::SHA PBKDF2 (macOS LibreSSL fallback — VERIFIED to match)
# The salt is passed as HEX so we never wrestle with binary on argv.
# ---------------------------------------------------------------------------
cas_pbkdf2_keyhex() {
  _pw="$1"; _salthex="$2"

  if cas_crypto_have python3; then
    CAS_PW="$_pw" CAS_SALTHEX="$_salthex" python3 - <<'PY'
import os, hashlib
pw   = os.environ['CAS_PW'].encode('utf-8')      # .NET string ctor also encodes UTF-8
salt = bytes.fromhex(os.environ['CAS_SALTHEX'])
print(hashlib.pbkdf2_hmac('sha1', pw, salt, 300000, 32).hex())
PY
    return $?
  fi

  # OpenSSL 3 only (LibreSSL prints an error here, which is why python/perl come first/after).
  # Note the two non-obvious flags learned empirically:
  #   -binary        -> emit raw key bytes (default would hexdump-with-colons differently)
  #   hexsalt:<hex>  -> salt is hex; `salt:<hex>` would (wrongly) treat the hex string as raw bytes
  if cas_crypto_have openssl && openssl kdf -help >/dev/null 2>&1; then
    openssl kdf -keylen 32 -binary \
      -kdfopt digest:SHA1 \
      -kdfopt pass:"$_pw" \
      -kdfopt hexsalt:"$_salthex" \
      -kdfopt iter:300000 PBKDF2 \
      | od -An -v -tx1 | tr -d ' \n'
    return $?
  fi

  # macOS / LibreSSL fallback: pure-perl PBKDF2-HMAC-SHA1 (VERIFIED bit-identical to the above).
  if cas_crypto_have perl; then
    CAS_PW="$_pw" CAS_SALTHEX="$_salthex" perl -MDigest::SHA=hmac_sha1 -e '
      my $pw   = $ENV{CAS_PW};
      my $salt = pack("H*", $ENV{CAS_SALTHEX});
      my ($iter,$dklen) = (300000, 32);
      my $out = ""; my $i = 1;
      while (length($out) < $dklen) {
        my $u = hmac_sha1($salt . pack("N",$i), $pw);   # U1
        my $t = $u;
        for (2..$iter) { $u = hmac_sha1($u, $pw); $t ^= $u; }  # XOR-fold U2..Uc
        $out .= $t; $i++;
      }
      print unpack("H*", substr($out,0,$dklen));
    '
    return $?
  fi

  echo "cas_pbkdf2_keyhex: no PBKDF2 backend (need python3, openssl 3, or perl Digest::SHA)" >&2
  return 1
}

# ---------------------------------------------------------------------------
# cas_encrypt <password> <out_path>   (plaintext token on STDIN)
#
# Generates a fresh random 16-byte salt + 16-byte iv, derives the key, AES-256-CBC/PKCS7
# encrypts stdin, and writes  salt || iv || ciphertext  to <out_path>.
#
# Implemented with python3 (preferred — single process, no token on argv) OR an openssl-only
# path (key fed as -K hex; iv as -iv hex; salt/iv generated by openssl rand).
# ---------------------------------------------------------------------------
cas_encrypt() {
  _pw="$1"; _out="$2"

  # Slurp the plaintext token from stdin into a variable. We CANNOT let python read stdin
  # directly when its program is supplied via `python3 - <<'PY'`, because the heredoc itself
  # becomes stdin and shadows the piped token. We base64-encode it to traverse the env var
  # safely (binary-clean; tokens are ASCII but this also tolerates any byte / no trailing NL).
  _plain_b64="$(base64 | tr -d '\n')"

  if cas_crypto_have python3; then
    # python3 path: program on argv (-c), secrets via env, plaintext via env (base64).
    # Nothing secret hits argv except the ephemeral derived KEY handed to the openssl child.
    CAS_PW="$_pw" CAS_OUT="$_out" CAS_PLAIN_B64="$_plain_b64" python3 -c '
import os, base64, hashlib, subprocess
pw    = os.environ["CAS_PW"].encode("utf-8")
out   = os.environ["CAS_OUT"]
plain = base64.b64decode(os.environ["CAS_PLAIN_B64"])
salt  = os.urandom(16)
iv    = os.urandom(16)
key   = hashlib.pbkdf2_hmac("sha1", pw, salt, 300000, 32)
ct = subprocess.run(
    ["openssl", "enc", "-aes-256-cbc", "-K", key.hex(), "-iv", iv.hex()],
    input=plain, stdout=subprocess.PIPE, check=True).stdout
with open(out, "wb") as f:
    f.write(salt + iv + ct)
'
    return $?
  fi

  # Pure-openssl fallback (no python3): generate salt/iv, derive key via cas_pbkdf2_keyhex,
  # then encrypt. We assemble salt|iv|ct by emitting the 32 header bytes (from hex, no xxd)
  # followed by the ciphertext stream.
  _salthex="$(openssl rand -hex 16)" || return 1
  _ivhex="$(openssl rand -hex 16)"   || return 1
  _keyhex="$(cas_pbkdf2_keyhex "$_pw" "$_salthex")" || return 1
  {
    # Emit the salt+iv prefix as raw bytes: turn "aabb.." into \xaa\xbb.. and printf it.
    printf '%b' "$(printf '%s%s' "$_salthex" "$_ivhex" | sed 's/\(..\)/\\x\1/g')"
    # Ciphertext: decode the captured base64 plaintext and pipe through openssl.
    printf '%s' "$_plain_b64" | base64 -d | openssl enc -aes-256-cbc -K "$_keyhex" -iv "$_ivhex"
  } > "$_out"
  return $?
}

# ---------------------------------------------------------------------------
# cas_decrypt <password> <in_path>  -> prints decrypted token to STDOUT (no newline)
#
# Builder self-test helper. The stick uses payload/decrypt.sh (same logic, standalone).
# Returns 1 on any failure (wrong password manifests as an openssl bad-decrypt/padding error).
# ---------------------------------------------------------------------------
cas_decrypt() {
  _pw="$1"; _in="$2"
  [ -f "$_in" ] || { echo "cas_decrypt: no such file: $_in" >&2; return 1; }

  # Read salt (bytes 0..15) and iv (bytes 16..31) as hex WITHOUT xxd (mac has no xxd).
  _salthex="$(head -c 16 "$_in" | od -An -v -tx1 | tr -d ' \n')"
  _ivhex="$(dd if="$_in" bs=1 skip=16 count=16 2>/dev/null | od -An -v -tx1 | tr -d ' \n')"
  _keyhex="$(cas_pbkdf2_keyhex "$_pw" "$_salthex")" || return 1

  # Ciphertext is everything from byte 32 onward (tail -c +33 = 1-based offset).
  tail -c +33 "$_in" | openssl enc -d -aes-256-cbc -K "$_keyhex" -iv "$_ivhex" 2>/dev/null
}
